### ISSUE TITLE
Bundle install not ran on Windows

### ISSUE THREAD

**Issue by xmik** [test-kitchen/busser-cucumber#9]
I have the following test/integration/default/cucumber/Gemfile:

```
source 'http://rubygems.org'

if /linux/ =~ RUBY_PLATFORM
  # not relevant
else
  gem 'rspec', '>= 3.2.0', :platform => [:x64_mingw]
  gem 'cucumber', '~> 1.3'
  gem 'aruba', '>= 0.6.2' 
  gem 'syntax' 
  gem 'rake'
end
```

when I run `kitchen verify default-windows-vagrant` (using kitchen-vagrant 0.18.0) I get the output:

```
-----> Starting Kitchen (v1.4.0)
-----> Verifying <default-windows-vagrant>...
       Preparing files for transfer
-----> Installing Busser (busser)
       Successfully installed thor-0.19.0
       Successfully installed busser-0.7.1
       2 gems installed
-----> Setting up Busser
       Creating BUSSER_ROOT in C:\Users\ADMINI~1\AppData\Local\Temp\verifier
       Creating busser binstub
       Installing Busser plugins: busser-cucumber
       Plugin cucumber installed (version 0.2.0)
-----> Running postinstall for cucumber plugin
       Suite path directory C:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites does not exist, skipping.
       Transferring files to <default-windows-vagrant>
-----> Running cucumber test suite
         run  PATH=C:\7-zip;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\opscode\chef\bin;C:\opscode\chef\embedded\bin:C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/bin; bundle install --local || bundle install from "."
$$$$$$ C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/bundler-1.9.9/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)
$$$$$$  from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/bundler-1.9.9/lib/bundler/spec_set.rb:85:in `map!'
$$$$$$  from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/bundler-1.9.9/lib/bundler/spec_set.rb:85:in `materialize'
$$$$$$  from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/bundler-1.9.9/lib/bundler/definition.rb:132:in `specs'
$$$$$$  from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/bundler-1.9.9/lib/bundler/definition.rb:177:in `specs_for'
$$$$$$  from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/bundler-1.9.9/lib/bundler/definition.rb:166:in `requested_specs'
$$$$$$  from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/bundler-1.9.9/lib/bundler/environment.rb:18:in `requested_specs'
$$$$$$  from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/bundler-1.9.9/lib/bundler/runtime.rb:13:in `setup'
$$$$$$  from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/bundler-1.9.9/lib/bundler.rb:122:in `setup'
$$$$$$  from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/bundler-1.9.9/lib/bundler/setup.rb:18:in `<top (required)>'
$$$$$$  from C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
$$$$$$  from C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
$$$$$$  from C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
$$$$$$  from C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/busser-cucumber-0.2.0/lib/busser/cucumber/runner.rb:20:in `<main>'
$$$$$$ !!!!!! Ruby Script [C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/busser-cucumber-0.2.0/lib/busser/cucumber/runner.rb C:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites/cucumber] exit code was 1
>>>>>> Verify failed on instance <default-windows-vagrant>.
>>>>>> Please see .kitchen/logs/default-windows-vagrant.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$env:BUSSER_ROOT = "$env:TEMP\verifier"
$env:GEM_HOME = "$env:TEMP\verifier\gems"
$env:GEM_PATH = "$env:TEMP\verifier\gems"
$env:GEM_CACHE = "$env:TEMP\verifier\gems\cache"

& $env:TEMP\verifier\bin\busser.bat test
]
>>>>>> ----------------------
```

When I check on Windows, in `C:/Users/Administrator/AppData/Local/Temp/verifier/gems/gems` the following gems are installed: 
![busser-cucumber-installed-gems](https://cloud.githubusercontent.com/assets/8240219/7772765/7f6c4c86-00a0-11e5-9040-da9725bb9d7a.png)
I see that [those lines](https://github.com/test-kitchen/busser-cucumber/blob/master/lib/busser/runner_plugin/cucumber.rb#L30) install latest bundler and cucumber gems, which is ok, but I think **bundle install was not ran at all**.  
### First solution attempt -- failed

My first thought was that PATH is invalid: 

```
run  PATH=C:\7-zip;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\opscode\chef\bin;C:\opscode\chef\embedded\bin:C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/bin; bundle install --local || bundle install from "."
```

I found that [this line](https://github.com/test-kitchen/busser-cucumber/blob/master/lib/busser/runner_plugin/cucumber.rb#L59) must be responsible. So I replaced:

```
run("PATH=#{ENV['PATH']}:#{Gem.bindir}; " \
            'bundle install --local || bundle install')
```

with

```
windir = Gem.bindir.gsub("/","\\")
run("PATH=#{ENV['PATH']}:#{windir}; " \
            'bundle install --local || bundle install')
```

In result the PATH seems ok:

```
run  PATH=C:\7-zip;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\opscode\chef\bin;C:\opscode\chef\embedded\bin;C:\Users\ADMINI~1\AppData\Local\Temp\verifier\gems\bin; bundle install --local || bundle install from "."
```

but still the same error occurs.
### Second solution attempt -- success but unacceptable

I replaced the same lines with: `bundle install` (in backticks). Then:

```
$ bundle exec kitchen verify default-windows-vagrant
-----> Starting Kitchen (v1.4.0)
-----> Verifying <default-windows-vagrant>...
       Preparing files for transfer
-----> Busser installation detected (busser)
       Installing Busser plugins: busser-cucumber
       Plugin cucumber already installed
       Removing C:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites/cucumber
       Transferring files to <default-windows-vagrant>
-----> Running cucumber test suite
       Using the default profile...
       Feature: Run rake
         I can run rake tasks

         Scenario: Run rake task                             # C:\Users\ADMINI~1\AppData\Local\Temp\verifier\suites\cucumber\features\ai-ruby_rake.feature:4
           Given TestRakefile.rb with a rake task            # features/step_definitions/ai-ruby_rake_steps.rb:3
           And I run `rake default -f TestRakefile.rb`       # aruba-0.6.2/lib/aruba/cucumber.rb:93
             The system cannot find the file specified. (2) (Aruba::LaunchError)
             C:\Users\ADMINI~1\AppData\Local\Temp\verifier\suites\cucumber\features\ai-ruby_rake.feature:6:in `And I run `rake default -f TestRakefile.rb`'
           Then the stdout should contain "ran default task" # aruba-0.6.2/lib/aruba/cucumber.rb:246

       Failing Scenarios:
       cucumber C:\Users\ADMINI~1\AppData\Local\Temp\verifier\suites\cucumber\features\ai-ruby_rake.feature:4 # Scenario: Run rake task

       1 scenario (1 failed)
       3 steps (1 failed, 1 skipped, 1 passed)
       0m0.031s
$$$$$$ *** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
$$$$$$ !!!!!! Ruby Script [C:/Users/ADMINI~1/AppData/Local/Temp/verifier/gems/gems/busser-cucumber-0.2.0/lib/busser/cucumber/runner.rb C:/Users/ADMINI~1/AppData/Local/Temp/verifier/suites/cucumber] exit code was 1
>>>>>> Verify failed on instance <default-windows-vagrant>.
>>>>>> Please see .kitchen/logs/default-windows-vagrant.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$env:BUSSER_ROOT = "$env:TEMP\verifier"
$env:GEM_HOME = "$env:TEMP\verifier\gems"
$env:GEM_PATH = "$env:TEMP\verifier\gems"
$env:GEM_CACHE = "$env:TEMP\verifier\gems\cache"

& $env:TEMP\verifier\bin\busser.bat test
]
>>>>>> ----------------------
```

The above output did not contain output of `bundle install`, but in `C:/Users/Administrator/AppData/Local/Temp/verifier/gems/gems` there are needed gems installed (e.g. cucumber-1.3.19). Obviously that is not the way it should be fixed. I tried [busser-serverspec](https://github.com/test-kitchen/busser-serverspec) too and the `bundle install` part there just works. So maybe the [run_bundle_install](https://github.com/test-kitchen/busser-serverspec/blob/master/lib/busser/runner_plugin/serverspec.rb#L41) method can be borrowed from there (fixed thanks to  test-kitchen/test-kitchen#616).

**Comment by xmik** [comment]
I verified it is enough to replace body of the method [bundle_install](https://github.com/test-kitchen/busser-cucumber/blob/master/lib/busser/runner_plugin/cucumber.rb#L53) with:
```
gemfile_path = File.join(cuke_path, 'Gemfile')
return nil unless File.exist?(gemfile_path)
# Bundle install local completes quickly if the gems are already found
# locally it fails if it needs to talk to the internet. The || below is
# the fallback to the internet-enabled version. It's a speed optimization.
banner('Bundle Installing..')
ENV['PATH'] = [ENV['PATH'], Gem.bindir, Config::CONFIG['bindir']].join(File::PATH_SEPARATOR)
bundle_install = "#{File.join(Config::CONFIG['bindir'], 'ruby')} " +
  "#{File.join(Gem.bindir, 'bundle')} install --gemfile #{gemfile_path}"
run("#{bundle_install} --local || #{bundle_install}")
```

**Comment by xmik** [comment]
I verified the above solution solves also my problem which happens on **Ubuntu**. The old implementation invokes system ruby for bundle install but uses different ruby to run tests:
```
run  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tmp/verifier/gems/bin; \ 
bundle install --local || bundle install from "."
```
and **when I have a gem listed in `test/integration/default/cucumber/Gemfile` which is already installed in system ruby, it is not being installed by bundler to `/tmp/verifier/gems/gems`**.
The implementation from serverspec results in:
```
run  /opt/chef/embedded/bin/ruby /tmp/verifier/gems/bin/bundle install \ 
--gemfile /tmp/verifier/suites/cucumber/Gemfile --local \ 
|| /opt/chef/embedded/bin/ruby /tmp/verifier/gems/bin/bundle install \ 
--gemfile /tmp/verifier/suites/cucumber/Gemfile from "."
```
